# Outputs for FHE LLM Proxy infrastructure

output "cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.fhe_proxy.id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = aws_eks_cluster.fhe_proxy.arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.fhe_proxy.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_eks_cluster.fhe_proxy.vpc_config[0].cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_id                         = aws_eks_cluster.fhe_proxy.id
    endpoint                          = aws_eks_cluster.fhe_proxy.endpoint
    ca_certificate                    = aws_eks_cluster.fhe_proxy.certificate_authority[0].data
    region                           = var.aws_region
  }
}

output "ecr_repository_url" {
  description = "URL of the ECR repository"
  value       = aws_ecr_repository.fhe_proxy.repository_url
}

output "load_balancer_dns" {
  description = "DNS name of the load balancer"
  value       = aws_lb.fhe_proxy.dns_name
}

output "vpc_id" {
  description = "ID of the VPC"
  value       = aws_vpc.fhe_proxy.id
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = aws_subnet.private[*].id
}

output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = aws_subnet.public[*].id
}

output "database_endpoint" {
  description = "Database endpoint"
  value       = var.enable_rds ? aws_db_instance.fhe_proxy[0].endpoint : null
}

output "kms_key_id" {
  description = "KMS key ID for encryption"
  value       = aws_kms_key.eks.key_id
}