apiVersion: v1
kind: ConfigMap
metadata:
  name: fhe-proxy-config
  namespace: fhe-proxy
  labels:
    app.kubernetes.io/name: fhe-proxy
    app.kubernetes.io/component: config
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    workers = 4
    max_connections = 2000
    request_timeout_seconds = 300
    enable_cors = true
    cors_allowed_origins = ["https://yourapp.com"]
    cors_allowed_methods = ["GET", "POST", "OPTIONS"]
    cors_allowed_headers = ["Content-Type", "Authorization", "X-API-Key"]

    [encryption]
    poly_modulus_degree = 16384
    coeff_modulus_bits = [60, 40, 40, 60]
    scale_bits = 40
    security_level = 128
    key_rotation_hours = 24
    noise_budget_threshold = 10

    [llm]
    provider = "openai"
    endpoint = "https://api.openai.com/v1"
    timeout_seconds = 300
    max_retries = 3
    retry_backoff_ms = 1000
    max_tokens_per_request = 4096
    rate_limit_per_minute = 1000
    allowed_models = ["gpt-4", "gpt-3.5-turbo"]

    [privacy]
    epsilon_per_query = 0.1
    delta = 1e-5
    max_queries_per_user = 10000
    track_privacy_budget = true
    noise_multiplier = 1.1
    differential_privacy_enabled = true
    privacy_budget_reset_hours = 24

    [monitoring]
    metrics_enabled = true
    metrics_port = 9090
    trace_sampling_rate = 0.1
    log_level = "info"
    log_format = "json"
    performance_profiling = true
    export_prometheus_metrics = true

    [security]
    require_api_key = true
    api_key_header = "X-API-Key"
    api_key_min_length = 32
    jwt_expiry_hours = 24
    session_timeout_minutes = 60
    max_request_size_mb = 50
    max_text_length = 100000
    sanitize_input = true
    validate_utf8 = true
    global_rate_limit = 10000
    per_ip_rate_limit = 1000
    rate_limit_window_minutes = 1
    rate_limit_burst = 50
    enable_adaptive_rate_limiting = true
    require_https = false
    content_security_policy = "default-src 'self'"
    x_content_type_options = "nosniff"
    x_frame_options = "DENY"
    x_xss_protection = "1; mode=block"
    referrer_policy = "strict-origin-when-cross-origin"

    [scaling]
    fhe_pool_size = 8
    max_concurrent_operations = 500
    connection_timeout_seconds = 30
    idle_timeout_seconds = 300
    auto_scaling_enabled = true
    target_cpu_percent = 70.0
    target_queue_length = 100
    scale_up_threshold = 80.0
    scale_down_threshold = 40.0
    min_replicas = 3
    max_replicas = 20
    cooldown_period_seconds = 180
    ciphertext_cache_size = 10000
    cache_ttl_seconds = 7200
    cache_cleanup_interval_seconds = 300
    enable_redis_cache = true
    circuit_breaker_enabled = true
    failure_threshold = 10
    success_threshold = 5
    circuit_timeout_seconds = 60

    [compliance]
    gdpr_enabled = true
    ccpa_enabled = true
    hipaa_enabled = false
    audit_logs_enabled = true
    audit_log_retention_days = 2555
    data_encryption_at_rest = true
    pii_detection_enabled = true
    anonymization_enabled = true

    [feature_flags]
    experimental_algorithms = false
    advanced_privacy_modes = true
    batch_processing = true
    streaming_responses = true
    multi_tenant_support = true
    custom_model_support = true