apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhe-proxy
  namespace: fhe-system
  labels:
    app: fhe-proxy
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fhe-proxy
  template:
    metadata:
      labels:
        app: fhe-proxy
    spec:
      containers:
      - name: fhe-proxy
        image: ghcr.io/terragon-labs/fhe-proxy:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
