name: Feature Request
description: Suggest an idea for FHE LLM Proxy
labels: ["enhancement", "feature-request"]
assignees: ["product-team"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: I considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Performance optimization
        - Security enhancement
        - New encryption scheme
        - API improvement
        - Developer experience
        - Documentation
        - Monitoring/Observability
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for adoption
        - Critical - Blocking current usage
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature affect?
      options:
        - label: Performance
        - label: Security
        - label: Privacy
        - label: API compatibility
        - label: Resource usage
        - label: Developer experience

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. When using feature X, I need...
        2. For integration with Y, it would help to...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Performance impact < Y%
        - [ ] Backward compatible with existing API

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references