# Cargo audit configuration for security vulnerability scanning
[database]
auto-update = true
update-timeout = 30
stale-database-allowed = true

[advisories]
severity-threshold = "low"
informational = ["notice", "unmaintained", "unsound"]

[yanked]
enabled = true

[licenses]
enabled = true
allow = ["Apache-2.0", "MIT", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-DFS-2016"]
deny = ["GPL-2.0", "GPL-3.0", "AGPL-3.0", "LGPL-2.1", "LGPL-3.0"]

[bans]
enabled = true
multiple-versions = "warn"

[output]
format = "human"
show-tree = false
quiet = false
EOF < /dev/null
